### ISSUE TITLE
vpc-sc-demo: Status Dashboard Route DFCX switch should be disabled when VPC server not deployed

### ISSUE THREAD

**Issue by nicain** [GoogleCloudPlatform/contact-center-ai-samples#246]
Currently the "Route Dialogflow Through VPC Proxy?" switch is enabled in the Status Dashboard, even when the "Proxy Server" asset in in the Deployment Dashboard is not enabled. The get_status method for the switch should have a check that determines if the Service Directory route and the Proxy server are deployed, using the REST api.

**Comment by koverholt** [comment]
Closing as stale, please reopen as needed.
