### ISSUE TITLE
agent not providing response from data store.

### ISSUE THREAD

**Issue by javedhussain1729** [GoogleCloudPlatform/contact-center-ai-samples#517]

**Comment by koverholt** [comment]
Thanks for the bug report! I've fixed the issue with the sample data in https://github.com/googlecodelabs/feedback/issues/1278#issuecomment-1706664838, so you can try again with the new unstructured sample data.

If you continue to have issues indexing data, please file a bug in the Dialogflow CX bug tracker at https://issuetracker.google.com/issues?q=componentid:956347+%2B%20status:open so we can look at the details of why your data indexing is failing.
