### ISSUE TITLE
Wrong image capture in Chapter 4, section Check the agent's data store.

### ISSUE THREAD

**Issue by luguina** [GoogleCloudPlatform/contact-center-ai-samples#518]
In chapter [4. Configure the agent to answer blood eligibility FAQs](https://codelabs.developers.google.com/codelabs/dialogflow-generator#3), section _Check the agent's data store_ the image currently indicates that the source is a website (Australian Red Cross Lifeblood) but in the steps before we added the information from a GCS bucket. Therefore, the image should show the Unstructured Documents selection instead.

**Comment by koverholt** [comment]
The image has been corrected and updated in the codelab. Thanks so much for letting us know!
