### ISSUE TITLE
How to use dialogflow cx integration with terraform when there are various languages being used for the same dialogflow agent

### ISSUE THREAD

**Issue by mahesh-iyer** [GoogleCloudPlatform/contact-center-ai-samples#538]
@koverholt 

How do I export various locale (language code) specific resource settings to terraform? For example, in "es-es" locale, there could be a page with "Hola" readout whereas in "fr-fr", the same page could have "Bonjour" instead of "Hola" since we are dealing with French language now. This is how my dialogflow agent is built. Each locale has its language specific readouts.

See attached. For the same flow/page/route combination, "Agent says" option changes depending upon which language is selected - "de-de" or "en-us". How to export all language resources configured in dialogflow agent to terraform?

<img width="446" alt="Screenshot 2023-12-05 at 11 29 15 PM" src="https://github.com/GoogleCloudPlatform/contact-center-ai-samples/assets/31979681/d5185565-ab38-4d99-a636-f4a272331e90">

<img width="445" alt="Screenshot 2023-12-05 at 11 28 53 PM" src="https://github.com/GoogleCloudPlatform/contact-center-ai-samples/assets/31979681/11266ef8-8e0e-47d7-a888-9d24c84c948d">

**Comment by koverholt** [comment]
Thanks for reaching out! This repository provides sample code and examples for working with Terraform and Dialogflow CX, but doesn't get into details about all of the possible functionality in the Terraform modules such as managing different languages. So, it would be best to reach out to Google Cloud Support, the Google Cloud Community forums, or the Dialogflow Issue Tracker. You can find links to those resources here: https://cloud.google.com/dialogflow/docs/support/getting-support.
