### ISSUE TITLE
[dialogflow-generative-fallback]

### ISSUE THREAD

**Issue by shlocksh** [GoogleCloudPlatform/contact-center-ai-samples#542]
The hyperlink for Documentation for [Generative fallback](https://cloud.google.com/dialogflow/priv/docs/labs/generative-fallback?authuser=0) isn't opening.
![Screenshot (444)](https://github.com/GoogleCloudPlatform/contact-center-ai-samples/assets/159759937/c2bb7902-8223-4c4b-a30a-2eda9188c7f5)

**Comment by koverholt** [comment]
Thanks for letting us know! I've fixed the link in the [Generative Fallback codelab](https://codelabs.developers.google.com/codelabs/dialogflow-generative-fallback) to point to the correct documentation page at https://cloud.google.com/dialogflow/cx/docs/concept/generative/generative-fallback.
