### ISSUE TITLE
Clarify Webhook Tag in Documentation

### ISSUE THREAD

**Issue by yil532** [GoogleCloudPlatform/contact-center-ai-samples#68]
When creating webhook for my agent, I found it's lack of proper documentation on "tag" name.
Lots of questions came across my brain, ex. when I use webhook to call on this parameter, does this tag == my parameter name? If not, what does it mean and how to fill the field?
https://screenshot.googleplex.com/ArPRP7bmfa8AmQL

I could find some information from here: https://cloud.google.com/dialogflow/cx/docs/concept/webhook#webhook-python. But it still does not solve my question.

**Comment by aribray** [comment]
Good question! Check out [Quickstart: Create a webhook](https://cloud.google.com/dialogflow/cx/docs/quick/webhook#create_the_webhook). 

You can get the tag using `request.fulfillmentInfo.tag`, and call the corresponding function that handles that tag. The provided example has only one tag, but most agents would have many and use a switch case to determine which function is called.
